spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatic}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        hbm2ddl:
          auto: validate
    show-sql: true
    generate-ddl: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
