spring:
  application:
    name: chat-service
  config:
    import: configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8001}
  cloud:
    config:
      retry:
        initial-interval: 5000
        max-interval: 10000
      fail-fast: true

server:
  port: 0
