server:
  port: 0

spring:
  config:
    import: configserver:http://localhost:8001
  application:
    name: person-service

person:
  repository:
    find-by-id: select * from person where person.id = :id
    find-by-username: select * from person where person.username = :username
    delete-by-id: update person set deleted = true where person.id = :id
    find-by-username-auth: select * from person where person.username = :username and not person.deleted
